import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components";
import { NavBar, SideBar } from "@/components/layout";

export const metadata: Metadata = {
  title: "Mindustry Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" translate="no">
      <body>
        <Providers>
          <NavBar />
          <div className="flex h-full">
            <SideBar />
            <div className="relative w-full h-full overflow-auto pt-11">
              {children}
            </div>
          </div>
        </Providers>
        <SpeedInsights />
      </body>
    </html>
  );
}
