export enum BuildingsEnum {
  AirblastDrill = "AirblastDrill",
  LaserDrill = "LaserDrill",
  PneumaticDrill = "PneumaticDrill",
  MechanicalDrill = "MechanicalDrill",
  MechanicalPump = "MechanicalPump",
  ImpulsePump = "ImpulsePump",
  RotaryPump = "RotaryPump",
  OilExtractor = "OilExtractor",
  Cultivator = "Cultivator",
  WaterExtractor = "WaterExtractor",

  BlastMixer = "BlastMixer",
  CoalCentrifuge = "CoalCentrifuge",
  CryofluidMixer = "CryofluidMixer",
  Disassembler = "Disassembler",
  GraphitePress = "GraphitePress",
  Kiln = "Kiln",
  Melter = "Melter",
  MultiPress = "MultiPress",
  PhaseWeaver = "PhaseWeaver",
  PlastaniumCompressor = "PlastaniumCompressor",
  Pulverizer = "Pulverizer",
  PyratiteMixer = "PyratiteMixer",
  Separator = "Separator",
  SiliconCrucible = "SiliconCrucible",
  SiliconSmelter = "SiliconSmelter",
  SporePress = "SporePress",
  SurgeSmelter = "SurgeSmelter",

  AdditiveReconstructor = "AdditiveReconstructor",
  AirFactory = "AirFactory",
  ExponentialReconstructor = "ExponentialReconstructor",
  GroundFactory = "GroundFactory",
  MultiplicativeReconstructor = "MultiplicativeReconstructor",
  NavalFactory = "NavalFactory",
  TetrativeReconstructor = "TetrativeReconstructor",

  OverdriveProjector = "OverdriveProjector",
  OverdriveDome = "OverdriveDome"
}

export enum ResourcesEnum {
  Copper = "Copper",
  Lead = "Lead",
  Coal = "Coal",
  Sand = "Sand",
  Scrap = "Scrap",
  Titanium = "Titanium",
  Thorium = "Thorium",
  Graphite = "Graphite",
  Silicon = "Silicon",
  PhaseFabric = "PhaseFabric",
  SurgeAlloy = "SurgeAlloy",
  BlastCompound = "BlastCompound",
  Metaglass = "Metaglass",
  Plastanium = "Plastanium",
  Pyratite = "Pyratite",
  SporePod = "SporePod",

  Water = "Water",
  Slag = "Slag",
  Oil = "Oil",
  Cryofluid = "Cryofluid"
}

export enum UnitsEnum {
  // Surpulo
  Dagger = "Dagger",
  Mace = "Mace",
  Fortress = "Fortress",
  Scepter = "Scepter",
  Reign = "Reign",
  Nova = "Nova",
  Pulsar = "Pulsar",
  Quasar = "Quasar",
  Vela = "Vela",
  Corvus = "Corvus",
  Crawler = "Crawler",
  Atrax = "Atrax",
  Spiroct = "Spiroct",
  Arkyid = "Arkyid",
  Toxopid = "Toxopid",
  Flare = "Flare",
  Horizon = "Horizon",
  Zenith = "Zenith",
  Antumbra = "Antumbra",
  Eclipse = "Eclipse",
  Mono = "Mono",
  Poly = "Poly",
  Mega = "Mega",
  Quad = "Quad",
  Oct = "Oct",
  Risso = "Risso",
  Minke = "Minke",
  Bryde = "Bryde",
  Sei = "Sei",
  Omura = "Omura",
  Retusa = "Retusa",
  Oxynoe = "Oxynoe",
  Aegires = "Aegires",
  Cyerce = "Cyerce",
  Navanax = "Navanax",
}

export enum TilesEnum {
  Other = "Other",
  SaltFloor = "SaltFloor",
  SandFloor = "SandFloor",
  DarkSandFloor = "DarkSandFloor",
  ShaleFloor = "ShaleFloor",
  MagmaRock = "MagmaRock",
  HotRock = "HotRock",
  BasaltFloor = "BasaltFloor",
  GrassFloor = "GrassFloor",
  SnowFloor = "SnowFloor",
  IceSnowFloor = "IceSnowFloor",
  IceFloor = "IceFloor",
  RedIceFloor = "RedIceFloor",
  MudFloor = "MudFloor",
  DarkSandTaintedWaterFloor = "DarkSandTaintedWaterFloor",
  MossFloor = "MossFloor",
  TaintedWaterFloor = "TaintedWaterFloor",
  SporeMossFloor = "SporeMossFloor"
}

export enum BuildingTypes {
    Extractor = "Extractor",
    Factory = "Factory",
    Reconstructor = "Reconstructor",
    Beacon = "Beacon",
    Unit = "Unit"
}