export enum ExtractorsEnum {
  // Surpulo
  AirblastDrill = "AirblastDrill",
  CliffCrusher = "CliffCrusher",
  ImpulsePump = "ImpulsePump",
  LaserDrill = "LaserDrill",
  MechanicalDrill = "MechanicalDrill",
  MechanicalPump = "MechanicalPump",
  OilExtractor = "OilExtractor",
  PneumaticDrill = "PneumaticDrill",
  RotaryPump = "RotaryPump",
  TurbineCondenser = "TurbineCondenser",
  WaterExtractor = "WaterExtractor",

  // Erekir
  Cultivator = "Cultivator",
  EruptionDrill = "EruptionDrill",
  ImpactDrill = "ImpactDrill",
  LargePlasmaBore = "LargePlasmaBore",
  PlasmaBore = "PlasmaBore",
  ReinforcedPump = "ReinforcedPump",
  VentCondenser = "VentCondenser"
}

export enum FactoriesEnum {
  // Serpulo
  BlastMixer = "BlastMixer",
  CoalCentrifuge = "CoalCentrifuge",
  CryofluidMixer = "CryofluidMixer",
  Disassembler = "Disassembler",
  GraphitePress = "GraphitePress",
  Kiln = "Kiln",
  Melter = "Melter",
  MultiPress = "MultiPress",
  PhaseWeaver = "PhaseWeaver",
  PlastaniumCompressor = "PlastaniumCompressor",
  Pulverizer = "Pulverizer",
  PyratiteMixer = "PyratiteMixer",
  Separator = "Separator",
  SiliconCrucible = "SiliconCrucible",
  SiliconSmelter = "SiliconSmelter",
  SporePress = "SporePress",
  SurgeSmelter = "SurgeSmelter",

  // Erekir
  AtmosphericConcentrator = "AtmosphericConcentrator",
  CarbideCrucible = "CarbideCrucible",
  CyanogenSynthesizer = "CyanogenSynthesizer",
  Electrolyzer = "Electrolyzer",
  OxidationChamber = "OxidationChamber",
  PhaseSynthesizer = "PhaseSynthesizer",
  SiliconArcFurnace = "SiliconArcFurnace",
  SlagIncinerator = "SlagIncinerator",
  SurgeCrucible = "SurgeCrucible",

  // Heat
  ElectricHeater = "ElectricHeater",
  HeatRedirector = "HeatRedirector",
  HeatRouter = "HeatRouter",
  PhaseHeater = "PhaseHeater",
  SlagHeater = "SlagHeater",
}

export enum ResourcesEnum {
  // Items
  Copper = "Copper",
  Lead = "Lead",
  Coal = "Coal",
  Sand = "Sand",
  Titanium = "Titanium",
  Thorium = "Thorium",
  Scrap = "Scrap",
  Graphite = "Graphite",
  Silicon = "Silicon",
  PhaseFabric = "PhaseFabric",
  SurgeAlloy = "SurgeAlloy",
  BlastCompound = "BlastCompound",
  Metaglass = "Metaglass",
  Plastanium = "Plastanium",
  Pyratite = "Pyratite",
  SporePod = "SporePod",
  Beryllium = "Beryllium",
  Carbide = "Carbide",
  Oxide = "Oxide",
  Tungsten = "Tungsten",

  // Liquids
  Water = "Water",
  Slag = "Slag",
  Oil = "Oil",
  Cryofluid = "Cryofluid",
  Arkycite = "Arkycite",
  Neoplasm = "Neoplasm",
  Cyanogen = "Cyanogen",
  Hydrogen = "Hydrogen",
  Nitrogen = "Nitrogen",
  Ozone = "Ozone",
}

export enum UnitFactoriesEnum {
  // Surpulo
  AdditiveReconstructor = "AdditiveReconstructor",
  AirFactory = "AirFactory",
  ExponentialReconstructor = "ExponentialReconstructor",
  GroundFactory = "GroundFactory",
  MultiplicativeReconstructor = "MultiplicativeReconstructor",
  NavalFactory = "NavalFactory",
  TetrativeReconstructor = "TetrativeReconstructor",

  // Erekir
  MechAssembler = "MechAssembler",
  MechFabricator = "MechFabricator",
  MechRefabricator = "MechRefabricator",
  PrimeRefabricator = "PrimeRefabricator",
  ShipAssembler = "ShipAssembler",
  ShipFabricator = "ShipFabricator",
  ShipRefabricator = "ShipRefabricator",
  TankAssembler = "TankAssembler",
  TankFabricator = "TankFabricator",
  TankRefabricator = "TankRefabricator"
}

export enum UnitsEnum {
  // Surpulo
  Dagger = "Dagger",
  Mace = "Mace",
  Fortress = "Fortress",
  Scepter = "Scepter",
  Reign = "Reign",
  Nova = "Nova",
  Pulsar = "Pulsar",
  Quasar = "Quasar",
  Vela = "Vela",
  Corvus = "Corvus",
  Crawler = "Crawler",
  Atrax = "Atrax",
  Spiroct = "Spiroct",
  Arkyid = "Arkyid",
  Toxopid = "Toxopid",
  Flare = "Flare",
  Horizon = "Horizon",
  Zenith = "Zenith",
  Antumbra = "Antumbra",
  Eclipse = "Eclipse",
  Mono = "Mono",
  Poly = "Poly",
  Mega = "Mega",
  Quad = "Quad",
  Oct = "Oct",
  Risso = "Risso",
  Minke = "Minke",
  Bryde = "Bryde",
  Sei = "Sei",
  Omura = "Omura",
  Retusa = "Retusa",
  Oxynoe = "Oxynoe",
  Aegires = "Aegires",
  Cyerce = "Cyerce",
  Navanax = "Navanax",

  // Erekir
  Stell = "Stell",
  Locus = "Locus",
  Precept = "Precept",
  Vanquish = "Vanquish",
  Conquer = "Conquer",
  Merui = "Merui",
  Cleroi = "Cleroi",
  Anthicus = "Anthicus",
  Tecta = "Tecta",
  Collaris = "Collaris",
  Elude = "Elude",
  Avert = "Avert",
  Obviate = "Obviate",
  Quell = "Quell",
  Disrupt = "Disrupt"
}